### ISSUE TITLE
Observing single object fails on device but works in simulator

### ISSUE THREAD

**Issue by juggernate** [RxSwiftCommunity/RxRealm#42] opened 2016-11-09 16:38 UTC
If I run RxRealm_Example it works in simulator but I hit ```fatalError("At present you can't observe objects that don't have primary key.")``` when I try to run on device.

**Comment by stremsdoerfer** [comment] 2016-11-09 16:51
Just posted a similar issue. Nice to see that I'm not the only one. I believe the issue is the line above though. On `type(of:object)`

**Comment by juggernate** [comment] 2016-11-10 00:58
@JustaLab do you see a difference on simulator vs device?

**Comment by stremsdoerfer** [comment] 2016-11-10 08:11
@juggernate yes, it works fine in the simulator.

**Comment by icanzilb** [comment] 2016-11-10 16:16
confirmed, I'll look into it - very strange ...

**Comment by icanzilb** [comment] 2016-11-10 17:03
the crash comes from the Swift standard library, `type(of:)` more specifically when running on a device - we'll have to consider a workaround maybe 🤔

**Comment by GabrielCartier** [comment] 2016-11-18 05:24
Been running into this issue too.
I tried some workarounds without any success. 
The only option I have right now is to convert my single object calls to array calls and only get the first object. Not ideal but that does it for me right now.

**Comment by icanzilb** [comment] 2016-11-18 09:50
I've been debugging this and it seems some kind of a Swift runtime error, right now I have no solution but to remove the single object observing from RxRealm ... I'll give it another try and if I don't find a reasonable solution I'll have to remove it

**Comment by insidegui** [comment] 2016-11-18 14:44
Yeap, I am having the same issue. It crashes on device but works on the simulator.

**Comment by icanzilb** [comment] 2016-12-01 06:44
fixed in latest release

**Closed as completed by icanzilb** 2016-12-01 06:44 UTC
