### ISSUE TITLE
Observing single object Error

### ISSUE THREAD

**Issue by stremsdoerfer** [RxSwiftCommunity/RxRealm#43] opened 2016-11-09 16:49 UTC
Hey!
I'm getting an error while observing a single object:

Here's my object
```swift
class Album : Object{
    dynamic var id = 0
    dynamic var title = ""
    dynamic var artist = ""
    override static func primaryKey() -> String? {
        return "id"
    }
}
```

Here's the way I call it:
```swift
let realm = try! Realm()
  try! realm.write({
      realm.add(album, update: true)
  })
  return Observable.from(album)
```

There's a EXC_BAD_ACCESS line 344 in RxRealm.swift. `type(of:object)` fails

Any idea?
Thanks

**Comment by GabrielCartier** [comment] 2016-11-18 01:53
Duplicate of #42

**Comment by icanzilb** [comment] 2016-12-01 06:44
fixed in latest release

**Closed as completed by icanzilb** 2016-12-01 06:44 UTC
