### ISSUE TITLE
Dependency "RxRealm" has no shared framework schemes

### ISSUE THREAD

**Issue by DaisukeNagata** [RxSwiftCommunity/RxRealm#24] opened 2016-07-22 13:47 UTC
Wrote github "RxSwiftCommunity / RxRealm" ~> 1.0 in carthage, was the carthage update.
Such error came out .
If you believe this to be an error, please file an issue with the maintainers at https://github.com/RxSwiftCommunity/RxRealm/issues/new
Is there a correspondence ?

**Comment by icanzilb** [comment] 2016-07-22 13:53
Please post a comment if you find what the problem was 👍

**Comment by DaisukeNagata** [comment] 2016-07-22 14:01
Thank you for contacting us.😀

I use the carthage the RxRealm, was conducted .
But is such an error came out .

Skipped building RxRealm due to the error:
Dependency "RxRealm" has no shared framework schemes

Information contained in Cartfile, github "RxSwiftCommunity / RxRealm" ~> 1.0

Is there a way?
I want to use the RxRealm! ! !

**Comment by icanzilb** [comment] 2016-08-12 06:54
Did you find what the problem with Carthage was?

**Comment by denis-hoz** [comment] 2016-08-17 15:38
Got same error.
@daisukenagata did you fixed it?

**Comment by DaisukeNagata** [comment] 2016-08-17 20:57
Thank you contact .

In so was able to correspond CocoaPods, it was conducted over there .

Thank you when there is something also .

**Comment by yoneapp** [comment] 2016-08-21 12:50
Hi, I probably have solved the problem.
We had two problem.

Firstly, This project has the wrong 1.0.5 tag.
How about we do it like this?

```
$ git tag -d 1.0.5
Deleted tag '1.0.5' (was 361357a)
$ git push origin :1.0.5
 - [deleted]         1.0.5
```

Because, Carthage probably determine the latest is a big number in semantic versioning.

I would imagine 1.0.5 tag is mistake.
1.0.5 tag have less committed.

https://github.com/RxSwiftCommunity/RxRealm/tree/1.0.5
42 commits

https://github.com/RxSwiftCommunity/RxRealm/tree/0.1.8
68 commits

like this.

```
# Fork and Cartfile edited
github "yoneapp/RxRealm"

# Before
$ carthage update --platform iOS
...
*** Checking out RxRealm at "1.0.5"
...
Dependency "RxRealm" has no shared framework schemes for any of the platforms: iOS

# After
$ carthage update --platform iOS
...
*** Checking out RxRealm at "0.1.7"
...
error: use of unresolved identifier 'RealmObserver'
```

Secondly, edcd6c0a7eb05658b0251776689a7da8f3e22556 has not been released.
For that reason, I ran this command.

```
$ git tag 0.1.8 40ff66e23d9ab9e6bff4256b020cbf5cbad619b1
$ git push origin 0.1.8:0.1.8
 * [new tag]         0.1.8 -> 0.1.8
```

As a result,

```
# Before
$ carthage update --platform iOS
...
*** Checking out RxRealm at "0.1.7"
...
error: use of unresolved identifier 'RealmObserver'

# After
$ carthage update --platform iOS
...
*** Checking out RxRealm at "0.1.8"
...
success
```

Thanks.

**Comment by cleexiang** [comment] 2016-08-21 13:43
I have the same problem, how to fix?

**Comment by DaisukeNagata** [comment] 2016-08-21 16:59
Thank you amazing 

実際に、実施してみます！！！

**Comment by rustproofFish** [comment] 2016-08-21 18:28
I'm still having issues with this. Any ETA on a fix?

**Comment by gwynantj** [comment] 2016-08-25 15:12
The issue is `1.0.5` is tagged to a commit that pre-dates Carthage support.

Example if I do a git log inside the `Carthage/Checkouts/RxRealm` directory i get this:
![screen shot 2016-08-25 at 4 09 19 pm](https://cloud.githubusercontent.com/assets/2777576/17974543/681f5204-6ade-11e6-8f07-ea9a24086c2b.png)

As you can see the top most commit was tagged for the 22nd of May, but Carthage support wasn't added until the 27th of May.

All you need to do is cut another release i.e. `1.0.6` that points to the latest HEAD.

What I have done in the meantime is just point Carthage to `master` just to get stuff working:
`github "RxSwiftCommunity/RxRealm" "master"`

@icanzilb any issues with doing another release?

**Comment by icanzilb** [comment] 2016-08-25 15:29
@gwynantj I'll look into doing a new tag 👍

**Comment by icanzilb** [comment] 2016-08-25 15:32
I see what happened ... one of the releases has the wrong version number and this seems to screw up Carthage ...

**Comment by icanzilb** [comment] 2016-08-25 15:33
@gwynantj can you please check again, the latest (current) version of the pod should be `0.1.8` (not sure how it's called when it's intalled through cartage)

**Comment by gwynantj** [comment] 2016-08-25 15:47
@icanzilb sorry to be a pain but that tag is still missing 2 commits from master. 

`1.0.8` doesn't build because it complains about the below:
![screen shot 2016-08-25 at 4 46 09 pm](https://cloud.githubusercontent.com/assets/2777576/17975963/77f5c1e0-6ae3-11e6-849b-73b054ae6faa.png)

**Comment by icanzilb** [comment] 2016-08-25 15:51
ok got ya, just pushed a `0.1.9`, hopefully that fixes it

**Comment by denis-hoz** [comment] 2016-08-25 16:00
@icanzilb Thanks! No errors in log!

**Comment by gwynantj** [comment] 2016-08-25 16:01
Yup fixed. Thanks

**Comment by icanzilb** [comment] 2016-08-25 16:02
alrighty; sorry for the trouble folks - my mistake for pushing that wrong release version

**Closed as completed by icanzilb** 2016-08-25 16:02 UTC
